### ISSUE TITLE
SeeK-path structure bug

### ISSUE THREAD

**Issue by butterflycollector** [materialscloud-org/issues#27]
Hello,

I was using https://www.materialscloud.org/work/tools/seekpath and I came across a bug. When I try to load a 72 atom planar graphene structure a wrong geometry is always displayed. The COOD input for CP2K also represents the same buggy geometry. It is as if everything has been shifted in one of the directions. The molecule fits the cell, but the atom positions and bonding are different. As if one or two rows have disappeared from one side and appeared on the opposite. I tried to input with .xyz, .pdb and .POSCAR and there was a bug every time. I tried different cell dimensions, bigger and smaller, changed with different steps. I tried generating the geometry in different ways. - Nothing works.

I really like the software. More than this - I need it. Can you please fix this ?

**Comment by butterflycollector** [comment]
Here is a preview of the bug
![Screenshot from 2022-12-30 23-37-00](https://user-images.githubusercontent.com/63873512/210113298-5d64b77f-584d-414a-be4c-ed9c75aa0f6d.png)

**Comment by butterflycollector** [comment]
It happened again with a different structure: CoGaLa3Se7
![Screenshot from 2022-12-31 22-39-49](https://user-images.githubusercontent.com/63873512/210155275-ce014f47-9995-4126-973b-a44c259bd3d6.png)

**Comment by eimrek** [comment]
Dear @butterflycollector. I'm really sorry that this issue was unaddressed for so long. Due to a change of almost the whole Materials Cloud team, these issues were left unmonitored.

But specifically, regarding your issue, it just looks like the difference is just in visualizations and the underlying structure is the same (just the periodic atoms are in different cells).

I'm therefore closing this issue for now, but if you are sure of the problem, feel free to elaborate and upload a structure that demonstrates the issue.
