### ISSUE TITLE
Notebook extensions

### ISSUE THREAD

**Issue by edditler** [materialscloud-org/issues#3]
Can we install the [notebook extensions](https://github.com/ipython-contrib/jupyter_contrib_nbextensions) in the jupyterhub to get some advanced functionality in the notebooks like LaTeX support, tables of content and more?

**Comment by ltalirz** [comment]
I don't have a strong opinion on this, but this repository includes >50 notebook extensions and we should probably avoid bloating our jupyter stack unnecessarily. Perhaps it would be preferable to pick individual extensions to address individual needs (can you list a few use cases?).

Note that if you just want some of the "productivity" extensions for development purposes, you can of course install them on your personal jupyter account.

Let's see what @oschuett has to say...

**Comment by edditler** [comment]
The extensions for development purposes are good enough for me right now. I have tried installing them in my jupiter account, but ran into trouble.

```
pip install jupyter_contrib_nbextensions 
jupyter contrib nbextension install --user 
```

installs the packages fine, but then `jupyter contrib` fails: `Error executing Jupyter command 'contrib': [Errno 2] No such file or directory`.

I'm pretty sure this is connected to the PATHs python/pip and jupyter use. If I understand the installation correctly, the jupyterhub is running python3, while the notebooks use python2 kernels.
After installing `jupyter_contrib_nbextensions` (both in pip and pip3) both `python -m jupyter contrib` and `python3 -m jupyter contrib` fail to find the right files. Can you by chance point me to the right direction?

**Comment by oschuett** [comment]
The problem I see with contrib_nbextensions is that they extend Jupyter in a global fashion - similar to appmode they are always present. Furthermore, contrib_nbextensions  is a large collection of extensions. Hence, we would have to decided on a subset of extensions which we would then enable for everybody. Because, every user has to have the exact same environment as otherwise some apps might not work for every user.

Therefore, I would be rather careful with adding contrib_nbextensions. For Latex expressions we already have MathJax. And for small snippets you could use %javascript cells. For larger chunks of javascript I would suggest to write a custom ipywidget. The advantage of ipywidgets over the contrib_nbextensions is that they can be loaded on a per notebook-basis, which basically eliminates the risk of unwanted side-effects

**Comment by ltalirz** [comment]
@edditler For some reason, `pip install jupyter_contrib_nbextensions` installs the binaries in `~/.local/bin`, which is not in the `PATH`.
If you do `export PATH=~/.local/bin:$PATH`, you'll be able to run `jupyter contrib nbextension install --user`

Adding `~/.local/bin` to the `PATH` might be something we need to do system-wide... 

Let me know if there are any extensions that we should consider installing system-wide (with use cases, please), otherwise we can close this issue.

**Comment by ltalirz** [comment]
Closing for the moment, reopen if needed.
