### ISSUE TITLE
Keeping apps up to date

### ISSUE THREAD

**Issue by edditler** [materialscloud-org/issues#4]
Right now one has no easy way of seeing whether an app is up to date.
A check could look something like
```
foreach subdirectory in ~/apps/:
    ! cd subdirectory
    ! git fetch
    ! git status > tmpfile
    if 'behind by' in tmpfile:
        print subdirectory+' outdated.'
    ! rm tmpfile
```

and be extended to an auto-updater similarly (given that there are no conflicts).

Also a way of hard-updating is to go to the app manager and delete & install an app. A button could be included there to do both in one go.

Is someone already working on something like this or are we going to solve this another way?

**Comment by ltalirz** [comment]
You're welcome to make a pull request to the app-manager in mc-home.
I think the main challenge here is to keep the the code as simple and short as possible.

It might make sense to add a "Search Updates" button next to "Return Launcher".
Since this is going to be a rather slow process, I would avoid doing this on load and rather cache the results (e.g. in a `.app_status.json`). It could then determine, whether the app manager shows "(installed)" or "(outdated)" and whether a "Update" button is shown when on clicks on the app.

Anyhow, these are just ideas.
In the end, I think the main challenge is to keep the app slim and elegant.

**Comment by edditler** [comment]
https://github.com/materialscloud-org/mc-home/pull/5

> Since this is going to be a rather slow process, I would avoid doing this on load and rather cache the results.

I agree, that doing it on load would be a bad idea, since the appmanager isn't the most responsive app as it is. For now I didn't include a cache, so the apps are rechecked every time the user clicks "Check all for updates".

**Comment by ltalirz** [comment]
this has been addressed long ago by @yakutovicha 
try it on aiidalab-demo.materialscloud.org
